debug: False

providers:
  yandex_music:
    default: true
    title: "Яндекс.Музыка"
    username: <YOUR_YANDEX_LOGIN>
    password: <YOUR_YANDEX_PASSWORD>
    cache: ./cache

controllers:
  cli: true
  http:
    port: 5000
    token: SECRET
